//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _21._106_zavgorodnij_authorization.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int userID { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int roleID { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
